### ISSUE TITLE
NA96 base map

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellen-NA6-issues#16]
Base map for 96/97 miata. 

https://rusefi.com/online/view.php?msq=1086

**Change Trigger from NB1 to Miata NA**
<img width="293" alt="image" src="https://user-images.githubusercontent.com/82395131/175383020-0fc2660c-26c0-4644-ad4b-0eaff36335e1.png">

**Change Map from None to intMAP and set sensor type to mpxh6400ensor type to mpxh6400**
<img width="251" alt="image" src="https://user-images.githubusercontent.com/82395131/175383313-442036f7-0ae6-41b9-a2c7-114c1d872d09.png">

**turn alternator enabled off**
<img width="262" alt="image" src="https://user-images.githubusercontent.com/82395131/175383247-4008750a-a4a2-4574-a645-ac872db40012.png">

**Comment by rusefillc** [comment]
https://rusefi.com/online/diff.php?msq1=1088&msq2=1086

**Comment by rusefillc** [comment]
https://rusefi.com/online/diff.php?msq1=1089&msq2=1086

**Comment by rusefillc** [comment]
https://rusefi.com/online/diff.php?msq1=1090&msq2=1086

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports flow 256 or 265?

**Comment by rusefillc** [comment]
overall see diff report https://rusefi.com/online/diff.php?msq1=1090&msq2=1086 all the most obvious stuff is done, rest of differences are kind of open question
