### ISSUE TITLE
Headphone Jack

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellen-NA6-issues#3]
Please delete the Knock Headphone.  It is not longer needed and interferes with casting inside the case.  Deleting saves me 10 minutes per case for modifications.  Currently no one has used it other than myself for a quick test.  Knock logging via Tuner Studio is all we need.

**Comment by andreika-git** [comment]
The headphone jack is now DNP:
![image](https://user-images.githubusercontent.com/15104768/139656928-2fd59ae4-0302-40f5-86a9-15736c1633a4.png)

https://github.com/rusefi/hellen-NA8-96/commit/1a3876c121485f852842de0d53d7d5fa6c5cb9eb
