### ISSUE TITLE
96 unused pins compared to nb1

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellen-NA6-issues#4]
Below is list of unsused pins provided by @andreika-git when comparing NB1 to 96/97.  Right column is instructions for pins.

| IN_02S3  | **Unused**  |
| IN_KNOCK_RAW  | **Use 4A on options port.  Delete GND from 4A**  |
| IN_PRESSURE  | **Keep for optional connection at 2A**  |
| IN_EGR_BOOST  | **Keep for optional connection at 3S**  |
| OUT_VICS  | **Unused**  |
| IN_MAP  | **Unused**  |
| IN_NEUTRAL  | **Unused**  |
| OUT_ALT_WARNING  | **Unused**  |
| OUT_ALTERNATOR  | **Unused**  |
| IN_STEERING  | **This is pin 3P and is unused.**  |
| IN_VIGN  | **Tap into 3B or 3I**  |

**Comment by andreika-git** [comment]
Please reconsider deleting GND from 4A - it's needed for WBO (which uses a lot of current and needs a good additional ground). Do you have an alternative pin for the knock input? 1S maybe?

**Comment by BeerMoneyMotorsports** [comment]
4a is a ground connection for an external sensor.  the GND for wbo is 4k.  I do like your idea of using 1S as an output.  User can add a pin there very easily.  

Lets do this
1S- Knock Raw
2A- In pressure
3S- ?? another temp?

**Comment by BeerMoneyMotorsports** [comment]
@andreika-git do you have any other questions?

**Comment by andreika-git** [comment]
I think it's time for me to trace-route a pcb according to the schematics... And then we'll see...
