### ISSUE TITLE
Hellen 96/97 BOM parts shortages

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellen-NA6-issues#6]
7 total parts shortages shown.  2 are known and i have parts locally.   the other 5 require input.

1- U410 | MIC5205-3.3YM5 | SOT23-5 | MIC5205-3.3YM5-TR16V 350mV @ 150mA - - Fixed 3.3V SOT-23-5 Linear Voltage Regulators (LDO) ROHS
2- U420 | LMR14030 | SOP8 | LMR14030SDDAR - - 3.5A 40V SO-8_EP DC-DC Converters ROHS
3- J3 | MiniFit | Molex-39301020 | 39301020Through Hole Wire To Board / Wire To Wire Connector ROHS
4- U103,U480 | AP2331W-7 | SOT-23 | AP2331W-7SC59 Power Distribution Switches ROHS
5- R101,R107,... | 4.7k | R0603-4 | 4D03WGF4701T5E8 4 ±1% 1/16W ±200ppm/℃ 4.7kΩ 1206 Resistor Networks & Arrays ROHS

**Comment by andreika-git** [comment]
My proposals:
1 - U410 - LD2980ABM33TR_C262919
2 - U420 - LMR14020SDDAR_C187824
3 - J3 - X9357WR-2x01-N2SN_C38875   (not 100% the same, doesn't have a plastic peg, but fits)
4 - ... :(
5 - R101,R107,... - CRA034RF4K70P05Z_C149871

**Comment by BeerMoneyMotorsports** [comment]
I need some help finding this alternative that is now on shortage

Q300, Q301, Q302, Q303, Q304, Q313, Q314  -  
MFR.Part # PJM2319PSA
JLCPCB Part # C411720
Package SOT-23-3
Description 3.1A 3V 250uA 40V 0.08Ω 3.1A,10V P Channel 1.25W SOT-23 MOSFETs ROHS

**Comment by andreika-git** [comment]
Q300, Q301, Q302, Q303, Q304, Q313, Q314 - AO3401A_C15127
These are 30V, not 40V

**Comment by andreika-git** [comment]
Perhaps even better option is AP40P05_C2886385

**Comment by BeerMoneyMotorsports** [comment]
I am in need of an alternate of this part.  JLC screwed up my order and i need to redo it.  This is a new one.  

1-  U603 | REF3033 | SOT-23 | REF3033AIDBZR

**Comment by andreika-git** [comment]
Are you sure that this part is out of stock?
![image](https://user-images.githubusercontent.com/15104768/145210773-88760575-79a3-4b30-93ed-3fd69637acfd.png)

**Comment by BeerMoneyMotorsports** [comment]
@andreika-git it was low inventory yesterday when i placed the order.  They must have received a shipment overnight.  

![image](https://user-images.githubusercontent.com/82395131/145232192-9e07df0b-d4ed-463a-9da4-f5acc148132f.png)
